config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, only: %i[show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie_id, scope: :list_id
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    list = List.find(params[:list_id])
    movie = Movie.find(params[:bookmark][:movie])
    comment = params[:bookmark][:comment]
    @bookmark = Bookmark.new(comment: comment, movie: movie, list: list)
    @bookmark.save
    redirect_to list_path(list)
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(list), status: :see_other
  end

  # private

  # def bookmark_params
  #   params.require(:bookmark).permit(:comment, :movie, :list)
  # end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks

  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/create.html.erb
<h1>Bookmarks#create</h1>
<p>Find me in app/views/bookmarks/create.html.erb</p>

app/views/bookmarks/new.html.erb
<h1>Bookmarks new</h1>
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.input :movie, collection: Movie.all %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Lists index</h1>
    <p>Your favorite categories</p>
  </div>
</div>


<div class="container">
  <div class="grid">
    <% @lists.each do |list| %>

      <%= link_to list_path(list) do %>
        <% if list.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path list.photo.key %>)">
            <%= list.name %>
          </div>
        <% else %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url()">
            <%= list.name %>
          </div>
        <% end %>
      <% end %>

    <% end %>
    <%= link_to "Add a new list", :new_list, class: 'btn btn-ghost bouton-center' %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add a new list", class: "btn btn-primary" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<% @bookmarks.each do |bookmark| %>
  <%= bookmark.comment %>
  <%= bookmark.movie.title %>
  <img src="<%= bookmark.movie.poster_url %>" alt="<%= bookmark.movie.title %>">
  <%= link_to "Delete", bookmark_path(bookmark),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
<% end %>
<%= link_to 'Back to lists', root_path %>
<%= link_to 'Add a movie', new_list_bookmark_path(@list) %>